In [7]:
import numpy as np

In [13]:
a=np.random.randn(12288,150) 
b=np.random.randn(150,45)
c= np.dot(a,b)
c.shape

(12288, 45)

In [11]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)

In [8]:
a=np.array([[2,1],[1,3]])

a

array([[2, 1],
       [1, 3]])

In [9]:
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [10]:
a*a

array([[4, 1],
       [1, 9]])

In [12]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)
(a*b).shape

(4, 3)

In [4]:
A = np.array([[56 ,0,4,5],
              [5,7,8,9],
              [1,2,3,4]])

A

array([[56,  0,  4,  5],
       [ 5,  7,  8,  9],
       [ 1,  2,  3,  4]])

In [10]:
b = A.sum(axis=0)
b.shape

(4,)

In [12]:
A/np.reshape(b, (1,4))

array([[0.90322581, 0.        , 0.26666667, 0.27777778],
       [0.08064516, 0.77777778, 0.53333333, 0.5       ],
       [0.01612903, 0.22222222, 0.2       , 0.22222222]])